import os
print("\n\n")
print("This is Python script to upgrade my Linux Devnet Desktop")
print("\n\n")
os.system ("apt update && apt list --upgradable")
print("\n\n")
print("*************************************")
print("Check the list of upgradable packages")
print("and decide if you want upgrade or not")
print("*************************************")
print("\n\n")
#os.system ("sleep 10")
print("type y if you want to continue with upgrade or type n if you want to exit")
a=input()
while a!="y" and a!="n":
	try:
		print("\n\n")
		print("************************************************************")
		print("Type y if you want to continue or type n if you want to exit")
		print("or type Ctl+C to exit the program")
		print("************************************************************")
		print("\n\n")
		a=input()
	except ValueError:
		a=input()
while a=="n":
	print("\n\n")
	print("********************************")
	print("Linux packages were not upgraded")
	print("********************************")
	a="stop"
while a=="y": 
	os.system ("apt upgrade -y && exit")
	print("\n\n\n\n")
	print("************************")
	print("The upgrade is completed")
	print("************************")
	print("\n\n\n\n")
	print("************************")
	print("The package list update ")
	print("will start in 5 sec     ")
	print("************************")
	os.system ("sleep 5")
	print("\n\n\n\n")	
	os.system ("sudo apt update")
	os.system ("sudo -k")
	print("\n\n\n\n")
	print("************************************")
	print("The upgrade and update are completed")
	print("************************************")
	a="stop"

